--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
                                id integer NOT NULL,
                                cost double precision NOT NULL,
                                date timestamp(6) without time zone NOT NULL,
                                type character varying(255) NOT NULL,
                                weight integer NOT NULL,
                                provider_id integer,
                                CONSTRAINT product_type_check CHECK (((type)::text = ANY ((ARRAY['APPLE_ANTONOVKA'::character varying, 'APPLE_SPARTAN'::character varying, 'PEAR_BERGAMOT'::character varying, 'PEAR_CONFERENCE'::character varying])::text[])))
);


--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider (
                                 id integer NOT NULL,
                                 name character varying(255) NOT NULL
);


--
-- Name: provider_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supply (
                               id integer NOT NULL,
                               date timestamp(6) without time zone NOT NULL,
                               total_cost double precision,
                               total_weight integer,
                               provider_id integer
);


--
-- Name: supply_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supply_products (
                                        supply_id integer NOT NULL,
                                        products_id integer NOT NULL
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product (id, cost, date, type, weight, provider_id) FROM stdin;
1	22500	2026-03-03 04:00:00	APPLE_ANTONOVKA	125	1
2	12500	2026-03-03 04:00:00	APPLE_SPARTAN	75	1
3	32500	2026-03-03 04:00:00	APPLE_SPARTAN	322	2
4	3250	2026-04-03 04:00:00	APPLE_ANTONOVKA	32	2
5	3350	2026-04-12 04:00:00	PEAR_BERGAMOT	42	3
6	2350	2026-05-12 04:00:00	PEAR_CONFERENCE	32	3
\.


--
-- Data for Name: provider; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.provider (id, name) FROM stdin;
1	ООО Яблочки
2	ООО ТЫблочки
3	ООО Грушки
\.


--
-- Data for Name: supply; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.supply (id, date, total_cost, total_weight, provider_id) FROM stdin;
1	2026-03-03 04:00:00	35000	200	1
\.


--
-- Data for Name: supply_products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.supply_products (supply_id, products_id) FROM stdin;
1	1
1	2
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_id_seq', 6, true);


--
-- Name: provider_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.provider_id_seq', 3, true);


--
-- Name: supply_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.supply_id_seq', 1, true);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: provider provider_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider
    ADD CONSTRAINT provider_pkey PRIMARY KEY (id);


--
-- Name: supply supply_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply
    ADD CONSTRAINT supply_pkey PRIMARY KEY (id);


--
-- Name: supply_products fkeukb084vwkskukmp7blu94fcd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_products
    ADD CONSTRAINT fkeukb084vwkskukmp7blu94fcd FOREIGN KEY (products_id) REFERENCES public.product(id);


--
-- Name: product fkfmt6vehie8ep9pq0nnvv9een7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkfmt6vehie8ep9pq0nnvv9een7 FOREIGN KEY (provider_id) REFERENCES public.provider(id);


--
-- Name: supply fkloo573ekgsg3g6m3lmuhkp1mp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply
    ADD CONSTRAINT fkloo573ekgsg3g6m3lmuhkp1mp FOREIGN KEY (provider_id) REFERENCES public.provider(id);


--
-- Name: supply_products fkm7hc128tp4bvitavkwgqlooop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_products
    ADD CONSTRAINT fkm7hc128tp4bvitavkwgqlooop FOREIGN KEY (supply_id) REFERENCES public.supply(id);


--
-- PostgreSQL database dump complete
--

